export const currentUser = {
  id: 'me',
  name: 'Minh Anh',
  handle: 'minhanh.nguyen',
  initials: 'MA',
  color: 'violet',
  job: 'Product Designer tại Studio North',
  location: 'TP. Hồ Chí Minh',
  joined: 'Tham gia tháng 7, 2023',
  bio: 'Thiết kế trải nghiệm, mê những chuyến đi ngẫu hứng và một ly cà phê ngon ☕',
  friends: 1284,
  followers: 2400,
}

export const people = [
  {
    id: 'linh',
    name: 'Linh Nguyễn',
    initials: 'LN',
    color: 'rose',
    subtitle: 'UX Designer · Hà Nội',
    mutual: 24,
    online: true,
  },
  {
    id: 'khoa',
    name: 'Khoa Trần',
    initials: 'KT',
    color: 'teal',
    subtitle: 'Photographer · Đà Lạt',
    mutual: 18,
    online: true,
  },
  {
    id: 'vy',
    name: 'Vy Lê',
    initials: 'VL',
    color: 'amber',
    subtitle: 'Content Creator · Sài Gòn',
    mutual: 12,
    online: false,
  },
  {
    id: 'tuan',
    name: 'Tuấn Phạm',
    initials: 'TP',
    color: 'blue',
    subtitle: 'Software Engineer · Đà Nẵng',
    mutual: 32,
    online: true,
  },
  {
    id: 'ha',
    name: 'Hà Đỗ',
    initials: 'HĐ',
    color: 'pink',
    subtitle: 'Illustrator · Hà Nội',
    mutual: 9,
    online: false,
  },
  {
    id: 'quang',
    name: 'Quang Vũ',
    initials: 'QV',
    color: 'indigo',
    subtitle: 'Product Manager · Sài Gòn',
    mutual: 15,
    online: true,
  },
]

export const stories = [
  { id: 'story-me', author: currentUser, theme: 'create', label: 'Tạo tin' },
  {
    id: 'story-linh',
    author: people[0],
    theme: 'sunset',
    label: 'Linh Nguyễn',
  },
  {
    id: 'story-khoa',
    author: people[1],
    theme: 'mountain',
    label: 'Khoa Trần',
  },
  { id: 'story-vy', author: people[2], theme: 'lavender', label: 'Vy Lê' },
  { id: 'story-tuan', author: people[3], theme: 'forest', label: 'Tuấn Phạm' },
]

export const posts = [
  {
    id: 'post-1',
    author: people[0],
    time: '2 giờ',
    audience: 'Bạn bè',
    text: 'Cuối tuần này mình đã dành một ngày thật chậm để ngắm hoàng hôn. Đôi khi chỉ cần dừng lại một chút là đủ để thấy mọi thứ đẹp hơn. 🌅',
    media: 'sunset',
    mediaTitle: 'Những khoảnh khắc đáng nhớ',
    likes: 128,
    comments: 24,
    shares: 7,
  },
  {
    id: 'post-2',
    author: people[1],
    time: '5 giờ',
    audience: 'Công khai',
    text: 'Một góc bình yên ở Đà Lạt sáng nay. Sương mù, thông xanh và một chút nắng đầu ngày. Bạn đã có kế hoạch cho chuyến đi tiếp theo chưa? 🌿',
    media: 'mountain',
    mediaTitle: 'Đà Lạt, Việt Nam',
    likes: 86,
    comments: 12,
    shares: 3,
  },
  {
    id: 'post-3',
    author: people[2],
    time: 'Hôm qua',
    audience: 'Bạn bè',
    text: 'Một lời nhắc nhỏ: bạn không cần phải hoàn hảo để bắt đầu. Cứ bắt đầu, rồi mọi thứ sẽ tốt dần lên. ✨',
    media: null,
    likes: 203,
    comments: 31,
    shares: 14,
  },
]

export const profilePosts = [
  {
    id: 'profile-post-1',
    author: currentUser,
    time: '3 ngày',
    audience: 'Công khai',
    text: 'Một tuần đầy cảm hứng với những ý tưởng mới, những cuộc trò chuyện hay và thật nhiều cà phê. Cảm ơn mọi người đã luôn ở đây! 💙',
    media: 'creative',
    mediaTitle: 'Make something wonderful',
    likes: 94,
    comments: 18,
    shares: 4,
  },
  {
    id: 'profile-post-2',
    author: currentUser,
    time: '1 tuần',
    audience: 'Bạn bè',
    text: 'Có ai cũng thích những ngày mưa và một playlist thật hay như mình không? ☔🎧',
    media: null,
    likes: 61,
    comments: 11,
    shares: 2,
  },
]

export const reels = [
  {
    id: 'reel-1',
    author: people[1],
    title: 'Một buổi sáng ở Đà Lạt 🌿',
    track: 'Original audio · Khoa Trần',
    theme: 'mountain',
    likes: '12,8K',
    comments: '342',
  },
  {
    id: 'reel-2',
    author: people[0],
    title: 'Chậm lại một chút để thấy nhiều hơn ✨',
    track: 'Golden Hour · JVKE',
    theme: 'sunset',
    likes: '8,4K',
    comments: '219',
  },
  {
    id: 'reel-3',
    author: people[2],
    title: 'Những điều nhỏ làm ngày vui hơn 🌸',
    track: 'Original audio · Vy Lê',
    theme: 'lavender',
    likes: '6,2K',
    comments: '138',
  },
]

export const conversations = [
  {
    id: 'linh',
    person: people[0],
    preview: 'Hẹn gặp bạn chiều mai nhé! 😊',
    time: '12:42',
    unread: 2,
    messages: [
      {
        id: 'm1',
        from: 'linh',
        text: 'Chào Minh Anh! Dạo này bạn thế nào?',
        time: '12:35',
      },
      {
        id: 'm2',
        from: 'me',
        text: 'Mình ổn nè, cảm ơn bạn. Cuối tuần này đi cà phê không?',
        time: '12:38',
      },
      {
        id: 'm3',
        from: 'linh',
        text: 'Được chứ! Quán cũ hay thử chỗ mới?',
        time: '12:40',
      },
      {
        id: 'm4',
        from: 'me',
        text: 'Thử chỗ mới nhé, mình vừa lưu một quán rất xinh.',
        time: '12:41',
      },
      {
        id: 'm5',
        from: 'linh',
        text: 'Hẹn gặp bạn chiều mai nhé! 😊',
        time: '12:42',
      },
    ],
  },
  {
    id: 'khoa',
    person: people[1],
    preview: 'Mình gửi ảnh cho bạn rồi nha',
    time: '11:20',
    unread: 0,
    messages: [
      {
        id: 'm1',
        from: 'khoa',
        text: 'Đà Lạt hôm nay đẹp quá!',
        time: '11:16',
      },
      {
        id: 'm2',
        from: 'me',
        text: 'Nhìn ảnh là muốn xách ba lô đi ngay 😄',
        time: '11:18',
      },
      {
        id: 'm3',
        from: 'khoa',
        text: 'Mình gửi ảnh cho bạn rồi nha',
        time: '11:20',
      },
    ],
  },
  {
    id: 'vy',
    person: people[2],
    preview: 'Cảm ơn bạn nhiều 💕',
    time: 'Hôm qua',
    unread: 0,
    messages: [
      { id: 'm1', from: 'vy', text: 'Cảm ơn bạn nhiều 💕', time: 'Hôm qua' },
    ],
  },
  {
    id: 'tuan',
    person: people[3],
    preview: 'Ý tưởng đó rất hay!',
    time: 'Thứ 4',
    unread: 0,
    messages: [
      { id: 'm1', from: 'tuan', text: 'Ý tưởng đó rất hay!', time: 'Thứ 4' },
    ],
  },
]
